#!/usr/bin/bash
# Run all tests before commiting

BACKEND_DIR=swa
BACKEND_TEST_CMD="gradle test"

TRUE=0
FALSE=1

# Helper Command for aborting if a Command returns a Non-Null Exit-Code
abort_on_failure() {
    if [ $1 -ne $TRUE ] ; then
        exit 1
    fi
}

# Runs the Command given in $2 if any File in the Directory given in $1 changed.
# The Command is run in the Directory given in $1
# Returns TRUE if the Command was run, FALSE otherwise
run_cmd_if_changed() {
    # Git will check if any Files changed in the given Directory and return 0 if none did.
    git diff HEAD --exit-code --quiet --relative=$1/
    if [ $? -ne 0 ] ; then
        cd $1 && $2
        # If the Command fails abort the Commit
        abort_on_failure $?
        result=$TRUE
    else
        result=$FALSE
    fi
}

# Check if any Files changed in the Backend
# If any Files changed run JUnit Tests for the Java Backend
run_cmd_if_changed $BACKEND_DIR "$BACKEND_TEST_CMD"

# Run Jester Tests for the Svelte Front-End
# TODO
