
logging:
  level:
    web: DEBUG

springdoc:
  # API-Docs is an Endpoint where the Swagger-UI
  # gets the information about the Endpoints.
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true