
swa:
  token:
    expiration-duration: 1d
  api:
    base: /api

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    web: INFO

springdoc:
  # Disable Swagger in Production
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  profiles:
    active: 'prod'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/swa
    username: spring
    password: password
  jpa:
    hibernate:
      # Create Model Tables on Startup
      ddl-auto: create
  web:
    resources:
      # Disable static Resource Mapping
      add-mappings: false

  mail:
    host: TODO
    port: -1
    username: TODO
    password: TODO
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
